import { relations } from 'drizzle-orm';
import {
    boolean,
    integer,
    jsonb,
    pgTable,
    real,
    serial,
    text,
    timestamp
} from 'drizzle-orm/pg-core';

export const user = pgTable('user', {
	id: serial('id').primaryKey(),
	age: integer('age')
});

// Sverdle game results table
export const sverdleResults = pgTable('sverdle_results', {
	id: serial('id').primaryKey(),
	// Game state
	wordIndex: integer('word_index').notNull(), // Index of the word in the words array
	answer: text('answer').notNull(), // The correct answer word
	guesses: jsonb('guesses').$type<string[]>().notNull(), // Array of guessed words
	answers: jsonb('answers').$type<string[]>().notNull(), // Array of answer patterns (e.g., ['__x_c', 'x____'])
	// Game outcome
	won: boolean('won').notNull(), // Whether the player won
	attempts: integer('attempts').notNull(), // Number of attempts (guesses.length)
	// Metadata
	createdAt: timestamp('created_at').defaultNow().notNull(),
	completedAt: timestamp('completed_at'), // When the game ended
	// Optional: user/session identifier
	sessionId: text('session_id') // Cookie or session identifier
});

// Zodiac calculation results table
export const zodiacResults = pgTable('zodiac_results', {
	id: serial('id').primaryKey(),
	// Optional user information
	fullName: text('full_name'), // Full name (optional)
	lifeTrajectory: text('life_trajectory'), // Life trajectory assessment (optional)
	// Birth information
	birthDate: text('birth_date').notNull(), // Date string (YYYY-MM-DD)
	birthTime: text('birth_time').notNull(), // Time string (HH:MM)
	// Location information
	placeName: text('place_name').notNull(), // Display name of the place
	latitude: text('latitude').notNull(), // Latitude as string
	longitude: text('longitude').notNull(), // Longitude as string
	timezone: text('timezone'), // Timezone string if available
	// Calculated signs
	sunSign: text('sun_sign').notNull(), // Calculated sun sign
	ascendant: text('ascendant').notNull(), // Calculated ascendant/rising sign
	moonSign: text('moon_sign').notNull(), // Calculated moon sign
	// Planet positions (stored as JSON object)
	planets: jsonb('planets').$type<Record<string, { sign: string; house?: number }>>(),
	// Houses (stored as JSON array)
	houses: jsonb('houses').$type<Array<{ number: number; sign: string }>>().notNull(),
	// UTC time components used for calculations
	utcYear: integer('utc_year').notNull(),
	utcMonth: integer('utc_month').notNull(),
	utcDay: integer('utc_day').notNull(),
	utcHour: integer('utc_hour').notNull(),
	utcMinute: integer('utc_minute').notNull(),
	// AI-generated analysis (kept for backward compatibility)
	aiAnalysis: text('ai_analysis'), // In-depth mystical analysis generated by AI
	// Metadata
	createdAt: timestamp('created_at').defaultNow().notNull(),
	// Optional: user/session identifier
	sessionId: text('session_id') // Cookie or session identifier
});

// Detailed analysis records table - stores every analysis ever generated
export const analysisRecords = pgTable('analysis_records', {
	id: serial('id').primaryKey(),
	// Foreign key to zodiac_results
	zodiacResultId: integer('zodiac_result_id').references(() => zodiacResults.id, { onDelete: 'cascade' }).notNull(),
	// The complete analysis text
	analysisText: text('analysis_text').notNull(),
	// The full prompt sent to AI service
	fullPrompt: text('full_prompt').notNull(),
	// System message used
	systemMessage: text('system_message'),
	// AI API details
	model: text('model').notNull(), // e.g., 'sonar-pro'
	temperature: real('temperature'), // Temperature setting used
	maxTokens: integer('max_tokens'), // Max tokens setting
	// Token usage statistics
	promptTokens: integer('prompt_tokens'), // Tokens used in prompt
	completionTokens: integer('completion_tokens'), // Tokens used in completion
	totalTokens: integer('total_tokens'), // Total tokens used
	// Response metadata
	finishReason: text('finish_reason'), // Why the completion finished (e.g., 'stop', 'length')
	responseId: text('response_id'), // AI service response ID for tracking
	// Chart data snapshot (stored as JSON for reference)
	chartDataSnapshot: jsonb('chart_data_snapshot').$type<{
		fullName?: string | null;
		lifeTrajectory?: string | null;
		birthDate: string;
		birthTime: string;
		placeName: string;
		sunSign: string;
		ascendant: string;
		moonSign: string;
		planets: Record<string, { sign: string; house?: number }>;
		houses: Array<{ number: number; sign: string }>;
	}>(),
	// Analysis metadata
	analysisType: text('analysis_type').default('mystical'), // Type of analysis (e.g., 'mystical', 'detailed', 'brief')
	analysisVersion: text('analysis_version'), // Version identifier for analysis format
	// Timestamps
	createdAt: timestamp('created_at').defaultNow().notNull(),
	completedAt: timestamp('completed_at'), // When analysis generation completed
	// Optional: user/session identifier
	sessionId: text('session_id') // Cookie or session identifier
});

// Define relations
export const zodiacResultsRelations = relations(zodiacResults, ({ many }) => ({
	analysisRecords: many(analysisRecords)
}));

export const analysisRecordsRelations = relations(analysisRecords, ({ one }) => ({
	zodiacResult: one(zodiacResults, {
		fields: [analysisRecords.zodiacResultId],
		references: [zodiacResults.id]
	})
}));
